# Generated by Django 4.1.1 on 2022-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_desc', models.TextField()),
                ('act_name', models.CharField(max_length=30)),
                ('act_shname', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
