# Generated by Django 4.1.2 on 2022-11-23 06:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import welcomepg.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0002_acts_alter_user_contact_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acts',
            new_name='Act',
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('welcomepg.user',),
            managers=[
                ('auditor', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('welcomepg.user',),
            managers=[
                ('subcontractor', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='typeofusr',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Auditor', 'Auditor'), ('Subcontractor', 'Subcontractor')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acts', models.JSONField(default=welcomepg.models.create_json)),
                ('audit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to='welcomepg.auditor')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor', to='welcomepg.subcontractor')),
            ],
        ),
    ]
