# Generated by Django 4.1.2 on 2022-11-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('a_files', models.FileField(upload_to='')),
                ('a_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcomepg.act')),
                ('e_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcomepg.event')),
            ],
        ),
    ]
