# Generated by Django 4.1.2 on 2022-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0006_rename_a_files_uploadfile_f_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(max_length=30, null=True, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(max_length=30, null=True, verbose_name='Event Time'),
        ),
    ]
