# Generated by Django 4.1.2 on 2022-12-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0007_event_event_date_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='observation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='related',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(max_length=30, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(max_length=30, null=True, verbose_name='Event Time'),
        ),
    ]
