# Generated by Django 4.1.2 on 2022-12-16 10:22

from django.db import migrations, models
import welcomepg.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0008_uploadfile_observation_user_related_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='observation',
        ),
        migrations.AddField(
            model_name='event',
            name='observation',
            field=models.JSONField(default=welcomepg.models.obser_json),
        ),
    ]
